-- =====================================================================
-- Procedimientos del maestro de contratos (plantillas + clausulas).
-- =====================================================================

DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_CREAR;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_ACTUALIZAR;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_LISTAR;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_OBTENER;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_OBTENER_ACTIVA;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_CAMBIAR_ESTADO;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_CLAUSULA_AGREGAR;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_CLAUSULA_LISTAR;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_CLAUSULA_ACTUALIZAR;
DROP PROCEDURE IF EXISTS SP_RRHH_PLANTILLA_CLAUSULA_ELIMINAR;

DELIMITER $$

CREATE PROCEDURE SP_RRHH_PLANTILLA_CREAR(
    IN p_id_tipo_contrato INT UNSIGNED,
    IN p_id_tipo_pago_locador INT UNSIGNED,
    IN p_nombre VARCHAR(150),
    IN p_titulo_documento VARCHAR(200),
    IN p_parrafo_intro TEXT,
    IN p_id_usuario_creacion INT UNSIGNED,
    OUT p_id_plantilla INT UNSIGNED
)
BEGIN
    DECLARE v_id_activo INT UNSIGNED;
    SET v_id_activo = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'ESTADO_GENERAL' AND CODIGO = 'ACTIVO' LIMIT 1);

    INSERT INTO RRHH_CONTRATO_PLANTILLA (
        ID_TIPO_CONTRATO, ID_TIPO_PAGO_LOCADOR, NOMBRE, TITULO_DOCUMENTO, PARRAFO_INTRO,
        ID_ESTADO, USUARIO_CREACION
    ) VALUES (
        p_id_tipo_contrato, p_id_tipo_pago_locador, p_nombre, p_titulo_documento, p_parrafo_intro,
        v_id_activo, p_id_usuario_creacion
    );

    SET p_id_plantilla = LAST_INSERT_ID();
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_ACTUALIZAR(
    IN p_id_plantilla INT UNSIGNED,
    IN p_nombre VARCHAR(150),
    IN p_titulo_documento VARCHAR(200),
    IN p_parrafo_intro TEXT,
    IN p_id_usuario_modificacion INT UNSIGNED
)
BEGIN
    UPDATE RRHH_CONTRATO_PLANTILLA
       SET NOMBRE = p_nombre,
           TITULO_DOCUMENTO = p_titulo_documento,
           PARRAFO_INTRO = p_parrafo_intro,
           USUARIO_MODIFICACION = p_id_usuario_modificacion
     WHERE ID_PLANTILLA = p_id_plantilla;
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_LISTAR()
BEGIN
    SELECT p.ID_PLANTILLA, p.NOMBRE, p.TITULO_DOCUMENTO,
           p.ID_TIPO_CONTRATO, tc.CODIGO AS TIPO_CONTRATO_CODIGO, tc.DESCRIPCION AS TIPO_CONTRATO_DESCRIPCION,
           p.ID_TIPO_PAGO_LOCADOR, tp.CODIGO AS TIPO_PAGO_LOCADOR_CODIGO, tp.DESCRIPCION AS TIPO_PAGO_LOCADOR_DESCRIPCION,
           p.ID_ESTADO, e.CODIGO AS ESTADO_CODIGO
      FROM RRHH_CONTRATO_PLANTILLA p
      JOIN MAESTRO_MAESTRO tc ON tc.ID_MAESTRO = p.ID_TIPO_CONTRATO
      LEFT JOIN MAESTRO_MAESTRO tp ON tp.ID_MAESTRO = p.ID_TIPO_PAGO_LOCADOR
      JOIN MAESTRO_MAESTRO e ON e.ID_MAESTRO = p.ID_ESTADO
     ORDER BY tc.ORDEN, tp.ORDEN, p.NOMBRE;
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_OBTENER(
    IN p_id_plantilla INT UNSIGNED
)
BEGIN
    SELECT p.ID_PLANTILLA, p.NOMBRE, p.TITULO_DOCUMENTO, p.PARRAFO_INTRO,
           p.ID_TIPO_CONTRATO, tc.CODIGO AS TIPO_CONTRATO_CODIGO, tc.DESCRIPCION AS TIPO_CONTRATO_DESCRIPCION,
           p.ID_TIPO_PAGO_LOCADOR, tp.CODIGO AS TIPO_PAGO_LOCADOR_CODIGO, tp.DESCRIPCION AS TIPO_PAGO_LOCADOR_DESCRIPCION,
           p.ID_ESTADO, e.CODIGO AS ESTADO_CODIGO
      FROM RRHH_CONTRATO_PLANTILLA p
      JOIN MAESTRO_MAESTRO tc ON tc.ID_MAESTRO = p.ID_TIPO_CONTRATO
      LEFT JOIN MAESTRO_MAESTRO tp ON tp.ID_MAESTRO = p.ID_TIPO_PAGO_LOCADOR
      JOIN MAESTRO_MAESTRO e ON e.ID_MAESTRO = p.ID_ESTADO
     WHERE p.ID_PLANTILLA = p_id_plantilla;
END$$

-- Usada al generar el PDF de un contrato: resuelve la plantilla activa
-- para su regimen (p_id_tipo_pago_locador NULL para PLANILLA). Si hay mas
-- de una activa para el mismo regimen (no deberia, pero no se fuerza con
-- UNIQUE para no pelear con el patron de baja logica), gana la mas nueva.
CREATE PROCEDURE SP_RRHH_PLANTILLA_OBTENER_ACTIVA(
    IN p_id_tipo_contrato INT UNSIGNED,
    IN p_id_tipo_pago_locador INT UNSIGNED
)
BEGIN
    DECLARE v_id_activo INT UNSIGNED;
    SET v_id_activo = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'ESTADO_GENERAL' AND CODIGO = 'ACTIVO' LIMIT 1);

    SELECT p.ID_PLANTILLA, p.NOMBRE, p.TITULO_DOCUMENTO, p.PARRAFO_INTRO
      FROM RRHH_CONTRATO_PLANTILLA p
     WHERE p.ID_TIPO_CONTRATO = p_id_tipo_contrato
       AND (
            (p_id_tipo_pago_locador IS NULL AND p.ID_TIPO_PAGO_LOCADOR IS NULL) OR
            p.ID_TIPO_PAGO_LOCADOR = p_id_tipo_pago_locador
       )
       AND p.ID_ESTADO = v_id_activo
     ORDER BY p.FECHA_CREACION DESC
     LIMIT 1;
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_CAMBIAR_ESTADO(
    IN p_id_plantilla INT UNSIGNED,
    IN p_activo TINYINT,
    IN p_id_usuario_modificacion INT UNSIGNED
)
BEGIN
    DECLARE v_id_estado INT UNSIGNED;
    SET v_id_estado = (
        SELECT ID_MAESTRO FROM MAESTRO_MAESTRO
         WHERE TIPO_MAESTRO = 'ESTADO_GENERAL' AND CODIGO = IF(p_activo = 1, 'ACTIVO', 'INACTIVO')
         LIMIT 1
    );

    UPDATE RRHH_CONTRATO_PLANTILLA
       SET ID_ESTADO = v_id_estado,
           USUARIO_MODIFICACION = p_id_usuario_modificacion
     WHERE ID_PLANTILLA = p_id_plantilla;
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_CLAUSULA_AGREGAR(
    IN p_id_plantilla INT UNSIGNED,
    IN p_orden INT,
    IN p_titulo VARCHAR(200),
    IN p_contenido TEXT,
    IN p_id_usuario_creacion INT UNSIGNED,
    OUT p_id_clausula INT UNSIGNED
)
BEGIN
    DECLARE v_id_activo INT UNSIGNED;
    SET v_id_activo = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'ESTADO_GENERAL' AND CODIGO = 'ACTIVO' LIMIT 1);

    INSERT INTO RRHH_CONTRATO_PLANTILLA_CLAUSULA (ID_PLANTILLA, ORDEN, TITULO, CONTENIDO, ID_ESTADO, USUARIO_CREACION)
    VALUES (p_id_plantilla, p_orden, p_titulo, p_contenido, v_id_activo, p_id_usuario_creacion);

    SET p_id_clausula = LAST_INSERT_ID();
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_CLAUSULA_LISTAR(
    IN p_id_plantilla INT UNSIGNED
)
BEGIN
    DECLARE v_id_activo INT UNSIGNED;
    SET v_id_activo = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'ESTADO_GENERAL' AND CODIGO = 'ACTIVO' LIMIT 1);

    SELECT ID_CLAUSULA, ID_PLANTILLA, ORDEN, TITULO, CONTENIDO
      FROM RRHH_CONTRATO_PLANTILLA_CLAUSULA
     WHERE ID_PLANTILLA = p_id_plantilla AND ID_ESTADO = v_id_activo
     ORDER BY ORDEN, ID_CLAUSULA;
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_CLAUSULA_ACTUALIZAR(
    IN p_id_clausula INT UNSIGNED,
    IN p_orden INT,
    IN p_titulo VARCHAR(200),
    IN p_contenido TEXT
)
BEGIN
    UPDATE RRHH_CONTRATO_PLANTILLA_CLAUSULA
       SET ORDEN = p_orden,
           TITULO = p_titulo,
           CONTENIDO = p_contenido
     WHERE ID_CLAUSULA = p_id_clausula;
END$$

CREATE PROCEDURE SP_RRHH_PLANTILLA_CLAUSULA_ELIMINAR(
    IN p_id_clausula INT UNSIGNED
)
BEGIN
    DELETE FROM RRHH_CONTRATO_PLANTILLA_CLAUSULA WHERE ID_CLAUSULA = p_id_clausula;
END$$

DELIMITER ;
