-- =====================================================================
-- 002_area_rol_usuario.sql
-- Areas, roles (area + sub-rol) y usuarios.
-- =====================================================================

CREATE TABLE IF NOT EXISTS AREA (
    ID_AREA                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CODIGO                    VARCHAR(30)  NOT NULL,
    NOMBRE                    VARCHAR(100) NOT NULL,
    ID_ESTADO                 INT UNSIGNED NOT NULL,
    ORDEN                     INT          NOT NULL DEFAULT 0,
    FECHA_CREACION            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION        DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_AREA_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_AREA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- El sub-rol vive como fila real de ROL (no como valor de MAESTRO_MAESTRO)
-- porque participa en relaciones de negocio (permisos, horarios).
CREATE TABLE IF NOT EXISTS ROL (
    ID_ROL                    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_AREA                   INT UNSIGNED NOT NULL,
    CODIGO                     VARCHAR(50)  NOT NULL,
    NOMBRE                     VARCHAR(100) NOT NULL,
    NIVEL_JERARQUICO           INT          NOT NULL DEFAULT 100,
    ID_ESTADO                  INT UNSIGNED NOT NULL,
    ORDEN                      INT          NOT NULL DEFAULT 0,
    FECHA_CREACION             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION         DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_ROL_AREA_CODIGO UNIQUE (ID_AREA, CODIGO),
    CONSTRAINT FK_ROL_AREA FOREIGN KEY (ID_AREA) REFERENCES AREA (ID_AREA),
    CONSTRAINT FK_ROL_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USUARIO                     VARCHAR(50)  NOT NULL,
    CORREO                      VARCHAR(150) NOT NULL,
    CLAVE_HASH                  VARCHAR(255) NOT NULL,
    NOMBRES                     VARCHAR(100) NOT NULL,
    APELLIDOS                   VARCHAR(100) NOT NULL,
    ID_ESTADO_USUARIO           INT UNSIGNED NOT NULL,
    REQUIERE_CAMBIO_CLAVE        TINYINT(1)  NOT NULL DEFAULT 0,
    INTENTOS_FALLIDOS            INT         NOT NULL DEFAULT 0,
    FECHA_BLOQUEO                DATETIME    NULL,
    ULTIMO_LOGIN                 DATETIME    NULL,
    FECHA_CREACION                DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION            DATETIME   NULL ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_CREACION              INT UNSIGNED NULL,
    USUARIO_MODIFICACION          INT UNSIGNED NULL,
    CONSTRAINT UQ_USUARIO_LOGIN UNIQUE (USUARIO),
    CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_USUARIO_ESTADO FOREIGN KEY (ID_ESTADO_USUARIO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- N:M usuario <-> rol. Permite multi-rol; ES_PRINCIPAL marca el rol por
-- defecto que se usa para resolver horario/permisos cuando no se indica otro.
CREATE TABLE IF NOT EXISTS USUARIO_ROL (
    ID_USUARIO_ROL              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO                   INT UNSIGNED NOT NULL,
    ID_ROL                       INT UNSIGNED NOT NULL,
    ES_PRINCIPAL                 TINYINT(1)   NOT NULL DEFAULT 0,
    ID_ESTADO                    INT UNSIGNED NOT NULL,
    FECHA_ASIGNACION              DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_USUARIO_ROL UNIQUE (ID_USUARIO, ID_ROL),
    CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_USUARIO_ROL_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL),
    CONSTRAINT FK_USUARIO_ROL_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_USUARIO_ROL_USUARIO ON USUARIO_ROL (ID_USUARIO, ID_ESTADO);
