-- =====================================================================
-- 003_horario_sesion.sql
-- Horario laboral (por rol, con override opcional por usuario) y
-- sesiones de autenticacion (server-side, la expiracion es dinamica
-- segun el horario vigente, no un TTL fijo).
-- =====================================================================

CREATE TABLE IF NOT EXISTS HORARIO_LABORAL (
    ID_HORARIO                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_ROL                      INT UNSIGNED NULL,
    ID_USUARIO                  INT UNSIGNED NULL,
    ID_DIA_SEMANA                INT UNSIGNED NOT NULL,
    HORA_INICIO                  TIME         NOT NULL,
    HORA_FIN                     TIME         NOT NULL,
    ID_ESTADO                    INT UNSIGNED NOT NULL,
    FECHA_CREACION                DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION            DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT CK_HORARIO_DUENO CHECK (ID_ROL IS NOT NULL OR ID_USUARIO IS NOT NULL),
    CONSTRAINT FK_HORARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL),
    CONSTRAINT FK_HORARIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_HORARIO_DIA FOREIGN KEY (ID_DIA_SEMANA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_HORARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_HORARIO_USUARIO_DIA ON HORARIO_LABORAL (ID_USUARIO, ID_DIA_SEMANA, ID_ESTADO);
CREATE INDEX IX_HORARIO_ROL_DIA ON HORARIO_LABORAL (ID_ROL, ID_DIA_SEMANA, ID_ESTADO);

CREATE TABLE IF NOT EXISTS SESION (
    ID_SESION                   CHAR(36)     NOT NULL PRIMARY KEY,
    ID_USUARIO                   INT UNSIGNED NOT NULL,
    TOKEN_HASH                    CHAR(64)    NOT NULL,
    IP_ORIGEN                     VARCHAR(45) NULL,
    USER_AGENT                    VARCHAR(255) NULL,
    FECHA_INICIO                   DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_ULTIMA_ACTIVIDAD          DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_EXPIRACION                DATETIME  NOT NULL,
    ID_ESTADO_SESION                 INT UNSIGNED NOT NULL,
    FECHA_CIERRE                     DATETIME NULL,
    CONSTRAINT UQ_SESION_TOKEN_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_SESION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_SESION_ESTADO FOREIGN KEY (ID_ESTADO_SESION) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_SESION_USUARIO_ESTADO ON SESION (ID_USUARIO, ID_ESTADO_SESION);
