-- =====================================================================
-- 004_aplicacion_permiso.sql
-- Registro unificado de modulos internos + apps externas, y la matriz
-- de permisos ROL x APLICACION que gobierna el RBAC.
-- =====================================================================

CREATE TABLE IF NOT EXISTS APLICACION (
    ID_APLICACION              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CODIGO                       VARCHAR(50)  NOT NULL,
    NOMBRE                       VARCHAR(100) NOT NULL,
    DESCRIPCION                  VARCHAR(300) NULL,
    ICONO                        VARCHAR(50)  NULL,
    ID_TIPO_APLICACION           INT UNSIGNED NOT NULL,
    RUTA_INTERNA                 VARCHAR(200) NULL,
    URL_EXTERNA                  VARCHAR(300) NULL,
    ID_AREA_PROPIETARIA          INT UNSIGNED NOT NULL,
    REQUIERE_SSO                 TINYINT(1)   NOT NULL DEFAULT 0,
    CLIENT_ID                    VARCHAR(100) NULL,
    CLIENT_SECRET_HASH           VARCHAR(255) NULL,
    ID_ESTADO                    INT UNSIGNED NOT NULL,
    ORDEN                        INT          NOT NULL DEFAULT 0,
    FECHA_CREACION                DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION            DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_APLICACION_CODIGO UNIQUE (CODIGO),
    CONSTRAINT FK_APLICACION_TIPO FOREIGN KEY (ID_TIPO_APLICACION) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_APLICACION_AREA FOREIGN KEY (ID_AREA_PROPIETARIA) REFERENCES AREA (ID_AREA),
    CONSTRAINT FK_APLICACION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ROL_APLICACION_PERMISO (
    ID_ROL_APLICACION_PERMISO   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_ROL                       INT UNSIGNED NOT NULL,
    ID_APLICACION                INT UNSIGNED NOT NULL,
    ID_NIVEL_PERMISO             INT UNSIGNED NOT NULL,
    PERMISOS_EXTRA               JSON         NULL,
    ID_ESTADO                    INT UNSIGNED NOT NULL,
    FECHA_CREACION                DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION            DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_ROL_APLICACION UNIQUE (ID_ROL, ID_APLICACION),
    CONSTRAINT FK_RAP_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL),
    CONSTRAINT FK_RAP_APLICACION FOREIGN KEY (ID_APLICACION) REFERENCES APLICACION (ID_APLICACION),
    CONSTRAINT FK_RAP_NIVEL FOREIGN KEY (ID_NIVEL_PERMISO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_RAP_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_RAP_APLICACION ON ROL_APLICACION_PERMISO (ID_APLICACION, ID_ESTADO);
