-- =====================================================================
-- 005_notificaciones.sql
-- Patron broadcast (NOTIFICACION) + fan-out por destinatario (NOTIFICACION_USUARIO).
-- =====================================================================

CREATE TABLE IF NOT EXISTS NOTIFICACION (
    ID_NOTIFICACION             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA                 INT UNSIGNED NOT NULL,
    TITULO                       VARCHAR(150) NOT NULL,
    MENSAJE                      VARCHAR(500) NOT NULL,
    ID_APLICACION_ORIGEN         INT UNSIGNED NULL,
    URL_DESTINO                  VARCHAR(300) NULL,
    ID_USUARIO_EMISOR            INT UNSIGNED NULL,
    FECHA_CREACION                DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_ESTADO                    INT UNSIGNED NOT NULL,
    CONSTRAINT FK_NOTIFICACION_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_NOTIFICACION_APLICACION FOREIGN KEY (ID_APLICACION_ORIGEN) REFERENCES APLICACION (ID_APLICACION),
    CONSTRAINT FK_NOTIFICACION_EMISOR FOREIGN KEY (ID_USUARIO_EMISOR) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_NOTIFICACION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS NOTIFICACION_USUARIO (
    ID_NOTIFICACION_USUARIO     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_NOTIFICACION              INT UNSIGNED NOT NULL,
    ID_USUARIO                   INT UNSIGNED NOT NULL,
    LEIDA                        TINYINT(1)   NOT NULL DEFAULT 0,
    FECHA_LECTURA                 DATETIME    NULL,
    FECHA_ENVIO                   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_NOTIFICACION_USUARIO UNIQUE (ID_NOTIFICACION, ID_USUARIO),
    CONSTRAINT FK_NU_NOTIFICACION FOREIGN KEY (ID_NOTIFICACION) REFERENCES NOTIFICACION (ID_NOTIFICACION),
    CONSTRAINT FK_NU_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_NU_USUARIO_LEIDA ON NOTIFICACION_USUARIO (ID_USUARIO, LEIDA, FECHA_ENVIO);
