-- =====================================================================
-- 007_rrhh_contratos.sql
-- Contratacion, contratos (planilla/locador), vencimientos y firma
-- digital via link publico. Ver detalle del flujo en el plan de diseno.
-- =====================================================================

-- Datos de identidad propios del modulo (no viven en USUARIO, que es
-- solo credenciales/identidad core), necesarios para redactar el contrato.
ALTER TABLE RRHH_EMPLEADO
    ADD COLUMN DNI VARCHAR(15) NULL AFTER ID_USUARIO,
    ADD COLUMN DIRECCION VARCHAR(200) NULL AFTER TELEFONO;

CREATE TABLE IF NOT EXISTS RRHH_CONTRATO (
    ID_CONTRATO                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO                   INT UNSIGNED NOT NULL,
    ID_TIPO_CONTRATO             INT UNSIGNED NOT NULL,
    ID_TIPO_PAGO_LOCADOR         INT UNSIGNED NULL,
    CARGO                        VARCHAR(100) NOT NULL,
    FUNCIONES                    TEXT NULL,
    FECHA_INICIO                 DATE NOT NULL,
    FECHA_FIN                    DATE NULL,
    SUELDO_MENSUAL                DECIMAL(10,2) NULL,
    TARIFA                        DECIMAL(10,2) NULL,
    NOMBRE_PROYECTO                VARCHAR(150) NULL,
    PERIODO_PAGO                   VARCHAR(100) NULL,
    NRO_CUENTA                     VARCHAR(30) NULL,
    CCI                            VARCHAR(30) NULL,
    BANCO                          VARCHAR(60) NULL,
    ID_ESTADO_CONTRATO             INT UNSIGNED NOT NULL,
    ID_CONTRATO_ANTERIOR           INT UNSIGNED NULL,
    TOKEN_FIRMA                    CHAR(36) NULL,
    TOKEN_EXPIRA                   DATETIME NULL,
    FIRMA_PNG_PATH                 VARCHAR(300) NULL,
    FECHA_FIRMA                    DATETIME NULL,
    DOCUMENTO_PATH                 VARCHAR(300) NULL,
    ID_ESTADO                      INT UNSIGNED NOT NULL,
    FECHA_CREACION                  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION              DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_CREACION                INT UNSIGNED NULL,
    CONSTRAINT UQ_RRHH_CONTRATO_TOKEN UNIQUE (TOKEN_FIRMA),
    CONSTRAINT FK_RRHH_CONTRATO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_RRHH_CONTRATO_TIPO FOREIGN KEY (ID_TIPO_CONTRATO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_RRHH_CONTRATO_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO_LOCADOR) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_RRHH_CONTRATO_ESTADO_CONTRATO FOREIGN KEY (ID_ESTADO_CONTRATO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_RRHH_CONTRATO_ANTERIOR FOREIGN KEY (ID_CONTRATO_ANTERIOR) REFERENCES RRHH_CONTRATO (ID_CONTRATO),
    CONSTRAINT FK_RRHH_CONTRATO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_RRHH_CONTRATO_USUARIO ON RRHH_CONTRATO (ID_USUARIO, ID_ESTADO);
CREATE INDEX IX_RRHH_CONTRATO_ESTADO_CONTRATO ON RRHH_CONTRATO (ID_ESTADO_CONTRATO, FECHA_FIN);
