-- =====================================================================
-- 016_pasivos.sql
-- Modulo de pasivos: deudas, prestamos, lineas de credito y letras
-- protestadas de la empresa, con su plan de pagos (cuotas).
--
-- Una cuota puede pagarse (genera un CUENTA_MOVIMIENTO de EGRESO,
-- enlazado via TIPO_REFERENCIA='PASIVO_CUOTA') o protestarse (letra
-- protestada -- estado de la cuota, no genera movimiento, no implica
-- una entidad legal aparte). PASIVO_CUOTA no tiene ID_ESTADO generico:
-- ID_ESTADO_CUOTA ya cubre ese rol (igual que RRHH_CONTRATO_CONCEPTO/
-- _PROYECTO, filas de detalle sin par de estados). Una cuota solo se
-- puede borrar de verdad mientras esta PENDIENTE; una vez PAGADA o
-- PROTESTADA ya no se borra, solo cambia de estado (no se pierde
-- historial de dinero movido o de un evento legal).
-- =====================================================================

CREATE TABLE IF NOT EXISTS PASIVO (
    ID_PASIVO                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_PASIVO           INT UNSIGNED NOT NULL,
    ACREEDOR                 VARCHAR(150) NOT NULL,
    DESCRIPCION              VARCHAR(300) NULL,
    NRO_OPERACION            VARCHAR(60)  NULL,
    MONTO_TOTAL              DECIMAL(14,2) NOT NULL,
    ID_MONEDA                INT UNSIGNED NOT NULL,
    TASA_INTERES             DECIMAL(5,2) NULL,
    FECHA_ORIGEN             DATE         NOT NULL,
    ID_CUENTA_PAGO           INT UNSIGNED NULL,
    ID_ESTADO_PASIVO         INT UNSIGNED NOT NULL,
    ID_ESTADO                INT UNSIGNED NOT NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION       DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_CREACION         INT UNSIGNED NULL,
    USUARIO_MODIFICACION     INT UNSIGNED NULL,
    CONSTRAINT FK_PASIVO_TIPO FOREIGN KEY (ID_TIPO_PASIVO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PASIVO_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PASIVO_CUENTA_PAGO FOREIGN KEY (ID_CUENTA_PAGO) REFERENCES CUENTA_EMPRESA (ID_CUENTA),
    CONSTRAINT FK_PASIVO_ESTADO_PASIVO FOREIGN KEY (ID_ESTADO_PASIVO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PASIVO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_PASIVO_TIPO_ESTADO ON PASIVO (ID_TIPO_PASIVO, ID_ESTADO_PASIVO);

CREATE TABLE IF NOT EXISTS PASIVO_CUOTA (
    ID_CUOTA                 INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_PASIVO                INT UNSIGNED NOT NULL,
    NRO_CUOTA                INT UNSIGNED NOT NULL,
    FECHA_VENCIMIENTO        DATE         NOT NULL,
    MONTO                    DECIMAL(14,2) NOT NULL,
    ID_ESTADO_CUOTA          INT UNSIGNED NOT NULL,
    ID_CUENTA_PAGO           INT UNSIGNED NULL,
    FECHA_PAGO               DATE         NULL,
    ID_MOVIMIENTO            INT UNSIGNED NULL,
    MOTIVO_PROTESTO          VARCHAR(300) NULL,
    FECHA_PROTESTO           DATE         NULL,
    USUARIO_CREACION         INT UNSIGNED NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION       DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_PASIVO_CUOTA_NRO UNIQUE (ID_PASIVO, NRO_CUOTA),
    CONSTRAINT FK_PASIVO_CUOTA_PASIVO FOREIGN KEY (ID_PASIVO) REFERENCES PASIVO (ID_PASIVO),
    CONSTRAINT FK_PASIVO_CUOTA_ESTADO FOREIGN KEY (ID_ESTADO_CUOTA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PASIVO_CUOTA_CUENTA_PAGO FOREIGN KEY (ID_CUENTA_PAGO) REFERENCES CUENTA_EMPRESA (ID_CUENTA),
    CONSTRAINT FK_PASIVO_CUOTA_MOVIMIENTO FOREIGN KEY (ID_MOVIMIENTO) REFERENCES CUENTA_MOVIMIENTO (ID_MOVIMIENTO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_PASIVO_CUOTA_ESTADO_FECHA ON PASIVO_CUOTA (ID_ESTADO_CUOTA, FECHA_VENCIMIENTO);
CREATE INDEX IX_PASIVO_CUOTA_CUENTA ON PASIVO_CUOTA (ID_CUENTA_PAGO);

-- Usado por Pasivos y por Compras para poder ver el historial de pagos
-- de un origen puntual (una cuota, una compra, un contrato) sin
-- escanear toda la tabla -- ver SP_CUENTA_MOVIMIENTO_LISTAR_POR_REFERENCIA.
CREATE INDEX IX_MOVIMIENTO_REFERENCIA ON CUENTA_MOVIMIENTO (TIPO_REFERENCIA, ID_REFERENCIA);
