-- =====================================================================
-- 017_compras.sql
-- Modulo de compras: catalogo de proveedores (bienes/servicios, no
-- personas bajo contrato -- eso ya lo cubre RRHH_CONTRATO) y sus
-- compras/facturas, con pagos parciales enlazados al libro de cuentas
-- via TIPO_REFERENCIA='COMPRA'.
--
-- PROVEEDOR es tabla propia (no fila de MAESTRO_MAESTRO) porque
-- necesita mas campos de los que ese catalogo generico soporta (RUC,
-- contacto, telefono, correo).
--
-- COMPRA_PAGO no tiene ID_ESTADO generico -- es una fila de detalle de
-- dinero ya movido, nunca se edita ni se borra, igual que
-- RRHH_CONTRATO_HORAS.
-- =====================================================================

CREATE TABLE IF NOT EXISTS PROVEEDOR (
    ID_PROVEEDOR             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RUC                      VARCHAR(11)  NULL,
    RAZON_SOCIAL             VARCHAR(150) NOT NULL,
    NOMBRE_CONTACTO          VARCHAR(100) NULL,
    TELEFONO                 VARCHAR(20)  NULL,
    CORREO                   VARCHAR(100) NULL,
    ID_ESTADO                INT UNSIGNED NOT NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION       DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_CREACION         INT UNSIGNED NULL,
    USUARIO_MODIFICACION     INT UNSIGNED NULL,
    CONSTRAINT FK_PROVEEDOR_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_PROVEEDOR_ESTADO ON PROVEEDOR (ID_ESTADO);

CREATE TABLE IF NOT EXISTS COMPRA (
    ID_COMPRA                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_PROVEEDOR             INT UNSIGNED NOT NULL,
    DESCRIPCION              VARCHAR(300) NOT NULL,
    NRO_DOCUMENTO            VARCHAR(30)  NULL,
    FECHA_COMPRA             DATE         NOT NULL,
    FECHA_VENCIMIENTO        DATE         NULL,
    MONTO_TOTAL              DECIMAL(14,2) NOT NULL,
    ID_MONEDA                INT UNSIGNED NOT NULL,
    ID_ESTADO_COMPRA         INT UNSIGNED NOT NULL,
    ID_ESTADO                INT UNSIGNED NOT NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION       DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_CREACION         INT UNSIGNED NULL,
    CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    CONSTRAINT FK_COMPRA_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_COMPRA_ESTADO_COMPRA FOREIGN KEY (ID_ESTADO_COMPRA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_COMPRA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_COMPRA_PROVEEDOR_ESTADO ON COMPRA (ID_PROVEEDOR, ID_ESTADO_COMPRA);

CREATE TABLE IF NOT EXISTS COMPRA_PAGO (
    ID_PAGO                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_COMPRA                INT UNSIGNED NOT NULL,
    FECHA_PAGO                DATE        NOT NULL,
    MONTO                    DECIMAL(14,2) NOT NULL,
    ID_CUENTA                INT UNSIGNED NOT NULL,
    ID_MOVIMIENTO            INT UNSIGNED NOT NULL,
    USUARIO_CREACION         INT UNSIGNED NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_COMPRA_PAGO_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA),
    CONSTRAINT FK_COMPRA_PAGO_CUENTA FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA_EMPRESA (ID_CUENTA),
    CONSTRAINT FK_COMPRA_PAGO_MOVIMIENTO FOREIGN KEY (ID_MOVIMIENTO) REFERENCES CUENTA_MOVIMIENTO (ID_MOVIMIENTO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_COMPRA_PAGO_COMPRA ON COMPRA_PAGO (ID_COMPRA);
