-- =====================================================================
-- 018_proyectos.sql
-- Modulo de proyectos/servicios: costeo y margen. Junta tres fuentes de
-- costo que hasta ahora vivian separadas -- mano de obra por hora de un
-- locador (RRHH_CONTRATO_PROYECTO/RRHH_CONTRATO_HORAS), compras de
-- equipos/servicios (COMPRA) y una asignacion manual de mano de obra
-- (planilla y cualquier otro tipo de pago que no se registra por hora) --
-- mas un libro de ingresos del proyecto (PROYECTO_INGRESO).
--
-- COSTO_PRESUPUESTADO/INGRESO_ESPERADO son campos manuales (lo que ya se
-- cotizo/acordo con el cliente): el dashboard compara lo real a hoy
-- contra estos dos numeros fijos para el margen "al cierre" -- no hay
-- proyeccion automatica por tendencia.
-- =====================================================================

CREATE TABLE IF NOT EXISTS PROYECTO (
    ID_PROYECTO              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO_PROYECTO         INT UNSIGNED NOT NULL,
    NOMBRE                   VARCHAR(150) NOT NULL,
    CLIENTE                  VARCHAR(150) NULL,
    DESCRIPCION              VARCHAR(300) NULL,
    FECHA_INICIO             DATE         NOT NULL,
    FECHA_FIN_ESTIMADA       DATE         NULL,
    COSTO_PRESUPUESTADO      DECIMAL(14,2) NOT NULL DEFAULT 0,
    INGRESO_ESPERADO         DECIMAL(14,2) NOT NULL DEFAULT 0,
    ID_MONEDA                INT UNSIGNED NOT NULL,
    ID_ESTADO_PROYECTO       INT UNSIGNED NOT NULL,
    ID_ESTADO                INT UNSIGNED NOT NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION       DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
    USUARIO_CREACION         INT UNSIGNED NULL,
    USUARIO_MODIFICACION     INT UNSIGNED NULL,
    CONSTRAINT FK_PROYECTO_TIPO FOREIGN KEY (ID_TIPO_PROYECTO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PROYECTO_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PROYECTO_ESTADO_PROYECTO FOREIGN KEY (ID_ESTADO_PROYECTO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO),
    CONSTRAINT FK_PROYECTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES MAESTRO_MAESTRO (ID_MAESTRO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_PROYECTO_TIPO_ESTADO ON PROYECTO (ID_TIPO_PROYECTO, ID_ESTADO_PROYECTO);

-- Sin cadena de saldo acumulado (a diferencia de CUENTA_MOVIMIENTO):
-- cualquier fila se puede borrar libremente, no hay guard de "solo la
-- mas reciente". ID_MOVIMIENTO es una reconciliacion opcional con el
-- ingreso real en Cuentas -- se deja mapeado, la UI para vincularlo
-- queda para despues.
CREATE TABLE IF NOT EXISTS PROYECTO_INGRESO (
    ID_INGRESO               INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_PROYECTO              INT UNSIGNED NOT NULL,
    FECHA                    DATE         NOT NULL,
    MONTO                    DECIMAL(14,2) NOT NULL,
    CONCEPTO                 VARCHAR(250) NOT NULL,
    ID_MOVIMIENTO            INT UNSIGNED NULL,
    USUARIO_CREACION         INT UNSIGNED NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PROYECTO_INGRESO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_PROYECTO_INGRESO_MOVIMIENTO FOREIGN KEY (ID_MOVIMIENTO) REFERENCES CUENTA_MOVIMIENTO (ID_MOVIMIENTO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_PROYECTO_INGRESO_PROYECTO ON PROYECTO_INGRESO (ID_PROYECTO);

-- Asignacion manual de mano de obra (planilla y cualquier tipo de pago
-- que no se registra por hora) -- ledger de solo insertar/borrar, sin
-- upsert, igual que RRHH_CONTRATO_HORAS/COMPRA_PAGO. ID_CONTRATO es
-- opcional: si la persona esta en RRHH se enlaza, si no (ej. un
-- subcontratista sin contrato en el sistema) se usa PERSONA_DESCRIPCION.
CREATE TABLE IF NOT EXISTS PROYECTO_COSTO_MANO_OBRA (
    ID_ASIGNACION            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_PROYECTO              INT UNSIGNED NOT NULL,
    ID_CONTRATO              INT UNSIGNED NULL,
    PERSONA_DESCRIPCION      VARCHAR(150) NULL,
    PERIODO                  VARCHAR(100) NOT NULL,
    MONTO                    DECIMAL(12,2) NOT NULL,
    CONCEPTO                 VARCHAR(250) NULL,
    USUARIO_CREACION         INT UNSIGNED NULL,
    FECHA_CREACION           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PROYECTO_MANO_OBRA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT FK_PROYECTO_MANO_OBRA_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES RRHH_CONTRATO (ID_CONTRATO)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE INDEX IX_PROYECTO_MANO_OBRA_PROYECTO ON PROYECTO_COSTO_MANO_OBRA (ID_PROYECTO);

-- Engancha los dos costos que ya existian en otros modulos al Proyecto
-- global, sin duplicar tablas.
ALTER TABLE COMPRA ADD COLUMN ID_PROYECTO INT UNSIGNED NULL AFTER ID_PROVEEDOR;
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO);
CREATE INDEX IX_COMPRA_PROYECTO ON COMPRA (ID_PROYECTO);

ALTER TABLE RRHH_CONTRATO_PROYECTO ADD COLUMN ID_PROYECTO INT UNSIGNED NULL AFTER ID_CONTRATO;
ALTER TABLE RRHH_CONTRATO_PROYECTO ADD CONSTRAINT FK_CONTRATO_PROYECTO_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO);
CREATE INDEX IX_CONTRATO_PROYECTO_PROYECTO ON RRHH_CONTRATO_PROYECTO (ID_PROYECTO);
