-- =====================================================================
-- Catalogos de identidad: tipo de documento, paises (lista completa,
-- generada desde la libreria i18n-iso-countries para evitar errores de
-- tipeo) y ciudades principales de los paises mas relevantes para la
-- contratacion de la empresa. No es una lista exhaustiva de ciudades --
-- RRHH puede agregar mas desde /administracion/maestros (tipo CIUDAD,
-- eligiendo el pais como "padre").
-- =====================================================================

SET @id_activo = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'ESTADO_GENERAL' AND CODIGO = 'ACTIVO');

INSERT INTO MAESTRO_MAESTRO (TIPO_MAESTRO, CODIGO, DESCRIPCION, ORDEN, ID_ESTADO) VALUES
    ('TIPO_DOCUMENTO_IDENTIDAD', 'DNI', 'DNI', 1, @id_activo),
    ('TIPO_DOCUMENTO_IDENTIDAD', 'CARNE_EXTRANJERIA', 'Carné de Extranjería', 2, @id_activo),
    ('TIPO_DOCUMENTO_IDENTIDAD', 'PASAPORTE', 'Pasaporte', 3, @id_activo),
    ('TIPO_DOCUMENTO_IDENTIDAD', 'RUC', 'RUC', 4, @id_activo),

    ('PAIS', 'AF', 'Afganistán', 0, @id_activo),
    ('PAIS', 'AL', 'Albania', 0, @id_activo),
    ('PAIS', 'DE', 'Alemania', 0, @id_activo),
    ('PAIS', 'AD', 'Andorra', 0, @id_activo),
    ('PAIS', 'AO', 'Angola', 0, @id_activo),
    ('PAIS', 'AI', 'Anguila', 0, @id_activo),
    ('PAIS', 'AQ', 'Antártida', 0, @id_activo),
    ('PAIS', 'AG', 'Antigua y Barbuda', 0, @id_activo),
    ('PAIS', 'SA', 'Arabia Saudita', 0, @id_activo),
    ('PAIS', 'DZ', 'Argelia', 0, @id_activo),
    ('PAIS', 'AR', 'Argentina', 0, @id_activo),
    ('PAIS', 'AM', 'Armenia', 0, @id_activo),
    ('PAIS', 'AW', 'Aruba', 0, @id_activo),
    ('PAIS', 'AU', 'Australia', 0, @id_activo),
    ('PAIS', 'AT', 'Austria', 0, @id_activo),
    ('PAIS', 'AZ', 'Azerbaiyán', 0, @id_activo),
    ('PAIS', 'BS', 'Bahamas', 0, @id_activo),
    ('PAIS', 'BH', 'Bahrein', 0, @id_activo),
    ('PAIS', 'BD', 'Bangladesh', 0, @id_activo),
    ('PAIS', 'BB', 'Barbados', 0, @id_activo),
    ('PAIS', 'BE', 'Bélgica', 0, @id_activo),
    ('PAIS', 'BZ', 'Belice', 0, @id_activo),
    ('PAIS', 'BJ', 'Benin', 0, @id_activo),
    ('PAIS', 'BM', 'Bermudas', 0, @id_activo),
    ('PAIS', 'BY', 'Bielorrusia', 0, @id_activo),
    ('PAIS', 'BO', 'Bolivia', 0, @id_activo),
    ('PAIS', 'BQ', 'Bonaire, San Eustaquio y Saba', 0, @id_activo),
    ('PAIS', 'BA', 'Bosnia y Herzegovina', 0, @id_activo),
    ('PAIS', 'BW', 'Botswana', 0, @id_activo),
    ('PAIS', 'BR', 'Brasil', 0, @id_activo),
    ('PAIS', 'BN', 'Brunei Darussalam', 0, @id_activo),
    ('PAIS', 'BG', 'Bulgaria', 0, @id_activo),
    ('PAIS', 'BF', 'Burkina Faso', 0, @id_activo),
    ('PAIS', 'BI', 'Burundi', 0, @id_activo),
    ('PAIS', 'BT', 'Bután', 0, @id_activo),
    ('PAIS', 'CV', 'Cabo Verde', 0, @id_activo),
    ('PAIS', 'KH', 'Camboya', 0, @id_activo),
    ('PAIS', 'CM', 'Camerún', 0, @id_activo),
    ('PAIS', 'CA', 'Canadá', 0, @id_activo),
    ('PAIS', 'QA', 'Catar', 0, @id_activo),
    ('PAIS', 'TD', 'Chad', 0, @id_activo),
    ('PAIS', 'CL', 'Chile', 0, @id_activo),
    ('PAIS', 'CN', 'China', 0, @id_activo),
    ('PAIS', 'CY', 'Chipre', 0, @id_activo),
    ('PAIS', 'CO', 'Colombia', 0, @id_activo),
    ('PAIS', 'KM', 'Comoras', 0, @id_activo),
    ('PAIS', 'CG', 'Congo', 0, @id_activo),
    ('PAIS', 'CD', 'Congo (República Democrática del)', 0, @id_activo),
    ('PAIS', 'CI', 'Costa de Marfil', 0, @id_activo),
    ('PAIS', 'CR', 'Costa Rica', 0, @id_activo),
    ('PAIS', 'HR', 'Croacia', 0, @id_activo),
    ('PAIS', 'CU', 'Cuba', 0, @id_activo),
    ('PAIS', 'CW', 'Curaçao', 0, @id_activo),
    ('PAIS', 'DK', 'Dinamarca', 0, @id_activo),
    ('PAIS', 'DM', 'Dominica', 0, @id_activo),
    ('PAIS', 'EC', 'Ecuador', 0, @id_activo),
    ('PAIS', 'EG', 'Egipto', 0, @id_activo),
    ('PAIS', 'SV', 'El Salvador', 0, @id_activo),
    ('PAIS', 'AE', 'Emiratos Árabes Unidos', 0, @id_activo),
    ('PAIS', 'ER', 'Eritrea', 0, @id_activo),
    ('PAIS', 'SK', 'Eslovaquia', 0, @id_activo),
    ('PAIS', 'SI', 'Eslovenia', 0, @id_activo),
    ('PAIS', 'ES', 'España', 0, @id_activo),
    ('PAIS', 'US', 'Estados Unidos', 0, @id_activo),
    ('PAIS', 'EE', 'Estonia', 0, @id_activo),
    ('PAIS', 'SZ', 'Esuatini', 0, @id_activo),
    ('PAIS', 'ET', 'Etiopía', 0, @id_activo),
    ('PAIS', 'FJ', 'Fiji', 0, @id_activo),
    ('PAIS', 'PH', 'Filipinas', 0, @id_activo),
    ('PAIS', 'FI', 'Finlandia', 0, @id_activo),
    ('PAIS', 'FR', 'Francia', 0, @id_activo),
    ('PAIS', 'GA', 'Gabón', 0, @id_activo),
    ('PAIS', 'GM', 'Gambia', 0, @id_activo),
    ('PAIS', 'GE', 'Georgia', 0, @id_activo),
    ('PAIS', 'GS', 'Georgia del Sur y las Islas Sandwich del Sur', 0, @id_activo),
    ('PAIS', 'GH', 'Ghana', 0, @id_activo),
    ('PAIS', 'GI', 'Gibraltar', 0, @id_activo),
    ('PAIS', 'GD', 'Granada', 0, @id_activo),
    ('PAIS', 'GR', 'Grecia', 0, @id_activo),
    ('PAIS', 'GL', 'Groenlandia', 0, @id_activo),
    ('PAIS', 'GP', 'Guadalupe', 0, @id_activo),
    ('PAIS', 'GU', 'Guam', 0, @id_activo),
    ('PAIS', 'GT', 'Guatemala', 0, @id_activo),
    ('PAIS', 'GF', 'Guayana Francesa', 0, @id_activo),
    ('PAIS', 'GG', 'Guernsey', 0, @id_activo),
    ('PAIS', 'GN', 'Guinea', 0, @id_activo),
    ('PAIS', 'GW', 'Guinea Bissau', 0, @id_activo),
    ('PAIS', 'GQ', 'Guinea Ecuatorial', 0, @id_activo),
    ('PAIS', 'GY', 'Guyana', 0, @id_activo),
    ('PAIS', 'HT', 'Haití', 0, @id_activo),
    ('PAIS', 'HM', 'Heard e Islas McDonald', 0, @id_activo),
    ('PAIS', 'HN', 'Honduras', 0, @id_activo),
    ('PAIS', 'HK', 'Hong Kong', 0, @id_activo),
    ('PAIS', 'HU', 'Hungría', 0, @id_activo),
    ('PAIS', 'IN', 'India', 0, @id_activo),
    ('PAIS', 'ID', 'Indonesia', 0, @id_activo),
    ('PAIS', 'IR', 'Irán', 0, @id_activo),
    ('PAIS', 'IQ', 'Iraq', 0, @id_activo),
    ('PAIS', 'IE', 'Irlanda', 0, @id_activo),
    ('PAIS', 'BV', 'Isla Bouvet', 0, @id_activo),
    ('PAIS', 'IM', 'Isla de Man', 0, @id_activo),
    ('PAIS', 'CX', 'Isla de Navidad', 0, @id_activo),
    ('PAIS', 'NF', 'Isla Norfolk', 0, @id_activo),
    ('PAIS', 'IS', 'Islandia', 0, @id_activo),
    ('PAIS', 'AX', 'Islas Åland', 0, @id_activo),
    ('PAIS', 'KY', 'Islas Caimán', 0, @id_activo),
    ('PAIS', 'CC', 'Islas Cocos (Keeling)', 0, @id_activo),
    ('PAIS', 'CK', 'Islas Cook', 0, @id_activo),
    ('PAIS', 'FO', 'Islas Feroe', 0, @id_activo),
    ('PAIS', 'FK', 'Islas Malvinas', 0, @id_activo),
    ('PAIS', 'MP', 'Islas Marianas del Norte', 0, @id_activo),
    ('PAIS', 'MH', 'Islas Marshall', 0, @id_activo),
    ('PAIS', 'SB', 'Islas Salomón', 0, @id_activo),
    ('PAIS', 'TC', 'Islas Turcas y Caicos', 0, @id_activo),
    ('PAIS', 'UM', 'Islas Ultramarinas Menores de los Estados Unidos', 0, @id_activo),
    ('PAIS', 'VG', 'Islas Vírgenes británicas', 0, @id_activo),
    ('PAIS', 'VI', 'Islas Vírgenes de los Estados Unidos', 0, @id_activo),
    ('PAIS', 'IL', 'Israel', 0, @id_activo),
    ('PAIS', 'IT', 'Italia', 0, @id_activo),
    ('PAIS', 'JM', 'Jamaica', 0, @id_activo),
    ('PAIS', 'JP', 'Japón', 0, @id_activo),
    ('PAIS', 'JE', 'Jersey', 0, @id_activo),
    ('PAIS', 'JO', 'Jordania', 0, @id_activo),
    ('PAIS', 'KZ', 'Kazajistán', 0, @id_activo),
    ('PAIS', 'KE', 'Kenia', 0, @id_activo),
    ('PAIS', 'KG', 'Kirguistán', 0, @id_activo),
    ('PAIS', 'KI', 'Kiribati', 0, @id_activo),
    ('PAIS', 'XK', 'Kosovo', 0, @id_activo),
    ('PAIS', 'KW', 'Kuwait', 0, @id_activo),
    ('PAIS', 'LS', 'Lesoto', 0, @id_activo),
    ('PAIS', 'LV', 'Letonia', 0, @id_activo),
    ('PAIS', 'LB', 'Líbano', 0, @id_activo),
    ('PAIS', 'LR', 'Liberia', 0, @id_activo),
    ('PAIS', 'LY', 'Libia', 0, @id_activo),
    ('PAIS', 'LI', 'Liechtenstein', 0, @id_activo),
    ('PAIS', 'LT', 'Lituania', 0, @id_activo),
    ('PAIS', 'LU', 'Luxemburgo', 0, @id_activo),
    ('PAIS', 'MO', 'Macao', 0, @id_activo),
    ('PAIS', 'MK', 'Macedonia del Norte', 0, @id_activo),
    ('PAIS', 'MG', 'Madagascar', 0, @id_activo),
    ('PAIS', 'MY', 'Malasia', 0, @id_activo),
    ('PAIS', 'MW', 'Malaui', 0, @id_activo),
    ('PAIS', 'MV', 'Maldivas', 0, @id_activo),
    ('PAIS', 'ML', 'Malí', 0, @id_activo),
    ('PAIS', 'MT', 'Malta', 0, @id_activo),
    ('PAIS', 'MA', 'Marruecos', 0, @id_activo),
    ('PAIS', 'MQ', 'Martinica', 0, @id_activo),
    ('PAIS', 'MU', 'Mauricio', 0, @id_activo),
    ('PAIS', 'MR', 'Mauritania', 0, @id_activo),
    ('PAIS', 'YT', 'Mayotte', 0, @id_activo),
    ('PAIS', 'MX', 'México', 0, @id_activo),
    ('PAIS', 'FM', 'Micronesia', 0, @id_activo),
    ('PAIS', 'MD', 'Moldavia', 0, @id_activo),
    ('PAIS', 'MC', 'Mónaco', 0, @id_activo),
    ('PAIS', 'MN', 'Mongolia', 0, @id_activo),
    ('PAIS', 'ME', 'Montenegro', 0, @id_activo),
    ('PAIS', 'MS', 'Montserrat', 0, @id_activo),
    ('PAIS', 'MZ', 'Mozambique', 0, @id_activo),
    ('PAIS', 'MM', 'Myanmar', 0, @id_activo),
    ('PAIS', 'NA', 'Namibia', 0, @id_activo),
    ('PAIS', 'NR', 'Nauru', 0, @id_activo),
    ('PAIS', 'NP', 'Nepal', 0, @id_activo),
    ('PAIS', 'NI', 'Nicaragua', 0, @id_activo),
    ('PAIS', 'NE', 'Níger', 0, @id_activo),
    ('PAIS', 'NG', 'Nigeria', 0, @id_activo),
    ('PAIS', 'NU', 'Niue', 0, @id_activo),
    ('PAIS', 'NO', 'Noruega', 0, @id_activo),
    ('PAIS', 'NC', 'Nueva Caledonia', 0, @id_activo),
    ('PAIS', 'NZ', 'Nueva Zelanda', 0, @id_activo),
    ('PAIS', 'OM', 'Omán', 0, @id_activo),
    ('PAIS', 'NL', 'Países Bajos', 0, @id_activo),
    ('PAIS', 'PK', 'Pakistán', 0, @id_activo),
    ('PAIS', 'PW', 'Palau', 0, @id_activo),
    ('PAIS', 'PS', 'Palestina', 0, @id_activo),
    ('PAIS', 'PA', 'Panamá', 0, @id_activo),
    ('PAIS', 'PG', 'Papua Nueva Guinea', 0, @id_activo),
    ('PAIS', 'PY', 'Paraguay', 0, @id_activo),
    ('PAIS', 'PE', 'Perú', 0, @id_activo),
    ('PAIS', 'PN', 'Pitcairn', 0, @id_activo),
    ('PAIS', 'PF', 'Polinesia Francesa', 0, @id_activo),
    ('PAIS', 'PL', 'Polonia', 0, @id_activo),
    ('PAIS', 'PT', 'Portugal', 0, @id_activo),
    ('PAIS', 'PR', 'Puerto Rico', 0, @id_activo),
    ('PAIS', 'GB', 'Reino Unido', 0, @id_activo),
    ('PAIS', 'SY', 'República Árabe Siria', 0, @id_activo),
    ('PAIS', 'CF', 'República Centroafricana', 0, @id_activo),
    ('PAIS', 'CZ', 'República Checa', 0, @id_activo),
    ('PAIS', 'KR', 'República de Corea', 0, @id_activo),
    ('PAIS', 'LA', 'República Democrática Popular de Lao', 0, @id_activo),
    ('PAIS', 'DO', 'República Dominicana', 0, @id_activo),
    ('PAIS', 'KP', 'República Popular Democrática de Corea', 0, @id_activo),
    ('PAIS', 'RE', 'Reunión', 0, @id_activo),
    ('PAIS', 'RW', 'Ruanda', 0, @id_activo),
    ('PAIS', 'RO', 'Rumanía', 0, @id_activo),
    ('PAIS', 'RU', 'Rusia', 0, @id_activo),
    ('PAIS', 'EH', 'Sahara Occidental', 0, @id_activo),
    ('PAIS', 'BL', 'Saint Barthélemy', 0, @id_activo),
    ('PAIS', 'KN', 'Saint Kitts y Nevis', 0, @id_activo),
    ('PAIS', 'MF', 'Saint Martin (francesa)', 0, @id_activo),
    ('PAIS', 'WS', 'Samoa', 0, @id_activo),
    ('PAIS', 'AS', 'Samoa Americana', 0, @id_activo),
    ('PAIS', 'SM', 'San Marino', 0, @id_activo),
    ('PAIS', 'PM', 'San Pedro y Miquelón', 0, @id_activo),
    ('PAIS', 'VC', 'San Vicente y las Granadinas', 0, @id_activo),
    ('PAIS', 'SH', 'Santa Helena, Ascensión y Tristán de Acuña', 0, @id_activo),
    ('PAIS', 'LC', 'Santa Lucía', 0, @id_activo),
    ('PAIS', 'VA', 'Santa Sede', 0, @id_activo),
    ('PAIS', 'ST', 'Santo Tomé y Príncipe', 0, @id_activo),
    ('PAIS', 'SN', 'Senegal', 0, @id_activo),
    ('PAIS', 'RS', 'Serbia', 0, @id_activo),
    ('PAIS', 'SC', 'Seychelles', 0, @id_activo),
    ('PAIS', 'SL', 'Sierra Leona', 0, @id_activo),
    ('PAIS', 'SG', 'Singapur', 0, @id_activo),
    ('PAIS', 'SX', 'Sint Maarten (neerlandesa)', 0, @id_activo),
    ('PAIS', 'SO', 'Somalia', 0, @id_activo),
    ('PAIS', 'LK', 'Sri Lanka', 0, @id_activo),
    ('PAIS', 'ZA', 'Sudáfrica', 0, @id_activo),
    ('PAIS', 'SD', 'Sudán', 0, @id_activo),
    ('PAIS', 'SS', 'Sudán del Sur', 0, @id_activo),
    ('PAIS', 'SE', 'Suecia', 0, @id_activo),
    ('PAIS', 'CH', 'Suiza', 0, @id_activo),
    ('PAIS', 'SR', 'Suriname', 0, @id_activo),
    ('PAIS', 'SJ', 'Svalbard y Jan Mayen', 0, @id_activo),
    ('PAIS', 'TH', 'Tailandia', 0, @id_activo),
    ('PAIS', 'TW', 'Taiwán', 0, @id_activo),
    ('PAIS', 'TZ', 'Tanzania', 0, @id_activo),
    ('PAIS', 'TJ', 'Tayikistán', 0, @id_activo),
    ('PAIS', 'IO', 'Territorio Británico del Océano Índico', 0, @id_activo),
    ('PAIS', 'TF', 'Tierras Australes Francesas', 0, @id_activo),
    ('PAIS', 'TL', 'Timor-Leste', 0, @id_activo),
    ('PAIS', 'TG', 'Togo', 0, @id_activo),
    ('PAIS', 'TK', 'Tokelau', 0, @id_activo),
    ('PAIS', 'TO', 'Tonga', 0, @id_activo),
    ('PAIS', 'TT', 'Trinidad y Tobago', 0, @id_activo),
    ('PAIS', 'TN', 'Túnez', 0, @id_activo),
    ('PAIS', 'TM', 'Turkmenistán', 0, @id_activo),
    ('PAIS', 'TR', 'Turquía', 0, @id_activo),
    ('PAIS', 'TV', 'Tuvalu', 0, @id_activo),
    ('PAIS', 'UA', 'Ucrania', 0, @id_activo),
    ('PAIS', 'UG', 'Uganda', 0, @id_activo),
    ('PAIS', 'UY', 'Uruguay', 0, @id_activo),
    ('PAIS', 'UZ', 'Uzbekistán', 0, @id_activo),
    ('PAIS', 'VU', 'Vanuatu', 0, @id_activo),
    ('PAIS', 'VE', 'Venezuela', 0, @id_activo),
    ('PAIS', 'VN', 'Vietnam', 0, @id_activo),
    ('PAIS', 'WF', 'Wallis y Futuna', 0, @id_activo),
    ('PAIS', 'YE', 'Yemen', 0, @id_activo),
    ('PAIS', 'DJ', 'Yibuti', 0, @id_activo),
    ('PAIS', 'ZM', 'Zambia', 0, @id_activo),
    ('PAIS', 'ZW', 'Zimbabue', 0, @id_activo);

-- Ciudades principales, solo para los paises mas relevantes para la
-- contratacion (Peru completo + LatAm/paises de origen migratorio
-- frecuente + algunos globales). No es exhaustivo -- ver nota arriba.
SET @pe = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'PE');
SET @ve = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'VE');
SET @co = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'CO');
SET @ec = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'EC');
SET @bo = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'BO');
SET @cl = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'CL');
SET @ar = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'AR');
SET @br = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'BR');
SET @mx = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'MX');
SET @us = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'US');
SET @es = (SELECT ID_MAESTRO FROM MAESTRO_MAESTRO WHERE TIPO_MAESTRO = 'PAIS' AND CODIGO = 'ES');

INSERT INTO MAESTRO_MAESTRO (TIPO_MAESTRO, ID_PADRE, CODIGO, DESCRIPCION, ORDEN, ID_ESTADO) VALUES
    ('CIUDAD', @pe, 'PE_LIMA', 'Lima', 1, @id_activo),
    ('CIUDAD', @pe, 'PE_AREQUIPA', 'Arequipa', 2, @id_activo),
    ('CIUDAD', @pe, 'PE_TRUJILLO', 'Trujillo', 3, @id_activo),
    ('CIUDAD', @pe, 'PE_CHICLAYO', 'Chiclayo', 4, @id_activo),
    ('CIUDAD', @pe, 'PE_PIURA', 'Piura', 5, @id_activo),
    ('CIUDAD', @pe, 'PE_IQUITOS', 'Iquitos', 6, @id_activo),
    ('CIUDAD', @pe, 'PE_CUSCO', 'Cusco', 7, @id_activo),
    ('CIUDAD', @pe, 'PE_CHIMBOTE', 'Chimbote', 8, @id_activo),
    ('CIUDAD', @pe, 'PE_HUANCAYO', 'Huancayo', 9, @id_activo),
    ('CIUDAD', @pe, 'PE_TACNA', 'Tacna', 10, @id_activo),
    ('CIUDAD', @pe, 'PE_ICA', 'Ica', 11, @id_activo),
    ('CIUDAD', @pe, 'PE_JULIACA', 'Juliaca', 12, @id_activo),
    ('CIUDAD', @pe, 'PE_SULLANA', 'Sullana', 13, @id_activo),
    ('CIUDAD', @pe, 'PE_AYACUCHO', 'Ayacucho', 14, @id_activo),
    ('CIUDAD', @pe, 'PE_CAJAMARCA', 'Cajamarca', 15, @id_activo),
    ('CIUDAD', @pe, 'PE_PUNO', 'Puno', 16, @id_activo),
    ('CIUDAD', @pe, 'PE_TUMBES', 'Tumbes', 17, @id_activo),
    ('CIUDAD', @pe, 'PE_JAEN', 'Jaén', 18, @id_activo),
    ('CIUDAD', @pe, 'PE_HUANUCO', 'Huánuco', 19, @id_activo),
    ('CIUDAD', @pe, 'PE_PUCALLPA', 'Pucallpa', 20, @id_activo),

    ('CIUDAD', @ve, 'VE_CARACAS', 'Caracas', 1, @id_activo),
    ('CIUDAD', @ve, 'VE_MARACAIBO', 'Maracaibo', 2, @id_activo),
    ('CIUDAD', @ve, 'VE_VALENCIA', 'Valencia', 3, @id_activo),
    ('CIUDAD', @ve, 'VE_BARQUISIMETO', 'Barquisimeto', 4, @id_activo),
    ('CIUDAD', @ve, 'VE_MARACAY', 'Maracay', 5, @id_activo),

    ('CIUDAD', @co, 'CO_BOGOTA', 'Bogotá', 1, @id_activo),
    ('CIUDAD', @co, 'CO_MEDELLIN', 'Medellín', 2, @id_activo),
    ('CIUDAD', @co, 'CO_CALI', 'Cali', 3, @id_activo),
    ('CIUDAD', @co, 'CO_BARRANQUILLA', 'Barranquilla', 4, @id_activo),
    ('CIUDAD', @co, 'CO_CARTAGENA', 'Cartagena', 5, @id_activo),

    ('CIUDAD', @ec, 'EC_QUITO', 'Quito', 1, @id_activo),
    ('CIUDAD', @ec, 'EC_GUAYAQUIL', 'Guayaquil', 2, @id_activo),
    ('CIUDAD', @ec, 'EC_CUENCA', 'Cuenca', 3, @id_activo),

    ('CIUDAD', @bo, 'BO_LAPAZ', 'La Paz', 1, @id_activo),
    ('CIUDAD', @bo, 'BO_SANTACRUZ', 'Santa Cruz de la Sierra', 2, @id_activo),
    ('CIUDAD', @bo, 'BO_COCHABAMBA', 'Cochabamba', 3, @id_activo),

    ('CIUDAD', @cl, 'CL_SANTIAGO', 'Santiago', 1, @id_activo),
    ('CIUDAD', @cl, 'CL_VALPARAISO', 'Valparaíso', 2, @id_activo),
    ('CIUDAD', @cl, 'CL_CONCEPCION', 'Concepción', 3, @id_activo),

    ('CIUDAD', @ar, 'AR_BUENOSAIRES', 'Buenos Aires', 1, @id_activo),
    ('CIUDAD', @ar, 'AR_CORDOBA', 'Córdoba', 2, @id_activo),
    ('CIUDAD', @ar, 'AR_ROSARIO', 'Rosario', 3, @id_activo),

    ('CIUDAD', @br, 'BR_SAOPAULO', 'São Paulo', 1, @id_activo),
    ('CIUDAD', @br, 'BR_RIODEJANEIRO', 'Río de Janeiro', 2, @id_activo),
    ('CIUDAD', @br, 'BR_BRASILIA', 'Brasilia', 3, @id_activo),

    ('CIUDAD', @mx, 'MX_CIUDADDEMEXICO', 'Ciudad de México', 1, @id_activo),
    ('CIUDAD', @mx, 'MX_GUADALAJARA', 'Guadalajara', 2, @id_activo),
    ('CIUDAD', @mx, 'MX_MONTERREY', 'Monterrey', 3, @id_activo),

    ('CIUDAD', @us, 'US_NUEVAYORK', 'Nueva York', 1, @id_activo),
    ('CIUDAD', @us, 'US_LOSANGELES', 'Los Ángeles', 2, @id_activo),
    ('CIUDAD', @us, 'US_MIAMI', 'Miami', 3, @id_activo),

    ('CIUDAD', @es, 'ES_MADRID', 'Madrid', 1, @id_activo),
    ('CIUDAD', @es, 'ES_BARCELONA', 'Barcelona', 2, @id_activo),
    ('CIUDAD', @es, 'ES_VALENCIA', 'Valencia', 3, @id_activo);
